version: '3.8'

services:
  # Zipkin for distributed tracing
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mem
      - MEM_MAX_SPANS=500000
    networks:
      - test-network

  # Selenium Grid Hub
  selenium-hub:
    image: selenium/hub:4.18.1
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - test-network

  # Chrome Node
  selenium-chrome:
    image: selenium/node-chrome:4.18.1
    container_name: selenium-chrome
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    networks:
      - test-network

  # Firefox Node
  selenium-firefox:
    image: selenium/node-firefox:4.18.1
    container_name: selenium-firefox
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    networks:
      - test-network

  # Edge Node
  selenium-edge:
    image: selenium/node-edge:4.18.1
    container_name: selenium-edge
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    networks:
      - test-network

  # Selenium Grid Router
  selenium-router:
    image: selenium/router:4.18.1
    container_name: selenium-router
    ports:
      - "4444:4444"
    depends_on:
      - selenium-hub
    environment:
      - SE_SESSION_QUEUE_TIMEOUT=300
      - SE_SESSION_REQUEST_TIMEOUT=300
    networks:
      - test-network

  # Selenium Grid Distributor
  selenium-distributor:
    image: selenium/distributor:4.18.1
    container_name: selenium-distributor
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - test-network

  # Selenium Grid Session Map
  selenium-session-map:
    image: selenium/session-map:4.18.1
    container_name: selenium-session-map
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - test-network

  # Selenium Grid Session Queue
  selenium-session-queue:
    image: selenium/session-queue:4.18.1
    container_name: selenium-session-queue
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - test-network

networks:
  test-network:
    driver: bridge 