version: '3.8'

services:
  # Zipkin Server - Distributed Tracing
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin-server
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mem
      - ZIPKIN_UI_DEFAULT_LOOKBACK=900000
      - ZIPKIN_UI_SEARCH_ENABLED=true
      - ZIPKIN_UI_DEPENDENCY_ENABLED=true
    networks:
      - zipkin-network
    restart: unless-stopped

networks:
  zipkin-network:
    driver: bridge

volumes:
  zipkin-data: 