server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Test Automation Logs
  - job_name: test-automation-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: test-automation
          __path__: /var/log/test-automation/*.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3}) \[(?P<thread>[^\]]+)\] (?P<level>\w+) +(?P<logger>[^ ]+) - (?P<message>.*)$'
      - labels:
          level:
          thread:
          logger:
      - timestamp:
          source: timestamp
          format: "2006-01-02 15:04:05.000"

  # DevTools Network Logs
  - job_name: devtools-network-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: devtools-network
          __path__: /var/log/test-automation/*.log
    pipeline_stages:
      - regex:
          expression: '.*DevTools.*HTTP.*Request.*'
      - labels:
          log_type: devtools_request
      - timestamp:
          source: timestamp
          format: "2006-01-02 15:04:05.000" 