global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # PushGateway - Selenium DevTools Network Metrics
  - job_name: 'pushgateway'
    honor_labels: true
    scrape_interval: 15s
    static_configs:
      - targets: ['pushgateway:9091']
    metrics_path: /metrics

  # Loki - Log Metrics
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  # Promtail - Log Collection Metrics
  - job_name: 'promtail'
    static_configs:
      - targets: ['promtail:9080'] 